### ISSUE TITLE
Add basic authentication

### ISSUE THREAD

**Issue by xnought** [xnought/venome#103]
## To start

- We can hard code a few accounts (create an accounts table in the DB)
- To start we can just make sure that only people logged in can make API requests (like upload, delete, edit)

Later on we can make it more complex

## Later on

We need accounts so that people

- create a new account with user and password available to anyone (not just OSU)
- stay logged in with cookies
- have elevated permission if they created a protein (so only they can delete, change, their protein).
- view all of their created proteins
- give multiple people permissions on one protein (like github where we can add contributors)
- let people without permission (not the protein owner or contributors) suggest changes (then the owner or contributor can accept or reject changes like github PRs)
- ...

Tasks:

## Subtasks
- [x] #110 
- [x] #129
- [x] #127 
- [x] #152 
- [x] #130 
- [x] #165 
- [x] #166 
- [x] #176 
- [x] #175 
- [x] #131 
- [x] #132 
- [x] #133

**Comment by xnought** [comment]
Any more ideas are appreciated, but ultimately up to whoever implements stuff / leads this feature

**Comment by xnought** [comment]
Probably the easiest way to implement this is to add a table in the backend for users and their hashed password. Then to login we can hash their entered passcode in the frontend, and compare against what we have stored.

**Comment by xnought** [comment]
Then we can have a permission table to see who owns which proteins

**Comment by ansengarvin** [comment]
Yeah, a "users" table would be a good way to do it. We could also add a column for a boolean "administrator" value - Only administrators can make other administrators.

**Comment by ansengarvin** [comment]
I updated the LucidChart schema based on what I think the User table could look like:

[](https://lucid.app/lucidchart/4958d57d-101d-4c33-aef3-717c381af45c/edit?invitationId=inv_94f4d938-33ba-4f8d-a758-4ac7f452a594&page=0_0#)

Proteins/Species have a one-to-many association with them: Each user can have many proteins, each protein can have one user with edit permissions. Admins can edit all proteins regardless of user status. I think this would be the easiest / simplest way to implement it for a prototype.

Additional Ideas / Future Considerations / Possible Stretch Goals:

There is an argument to be had for allowing a proteins to have multiple users associated with them - If a team of external protein researchers wants to be able to edit a single protein page on this website, it would be pretty annoying to be unable to do so from their personal accounts.

Adding additional users to a protein could look like something similar to GitHub. The flow could look like this:
1. User A creates a protein
2. User A views page for protein after creation, sees button called "Add additional editors"
3. User A is given the option to type in the name of an existing user, or send an email to another user
4. User A types in an email.
5. User B receives email, is prompted to make account
6. User B's account is added to the list of allowed editors of the protein page

We could also allow people to create "teams". Protein pages created under the umbrella of a team would automatically give all members of that team edit permissions in that protein. This is beneficial in a scenario where a team consisting of a group of users wants to add a bunch of proteins to the database - It would be pretty annoying to have to add a whole bunch of emails to every member of your group every time you have to create a protein, if you want to make a whole bunch of proteins.

**Comment by xnought** [comment]
Great point about teams
