### ISSUE TITLE
Look into PDB file format

### ISSUE THREAD

**Issue by xnought** [xnought/venome#13]
Look into what makes up the PDB format

**Comment by xnought** [comment]
@ansengarvin let us know when you can take a look at the PDB file format.

**Comment by xnought** [comment]
I'll also take a look

**Comment by xnought** [comment]
+ if we can download some pdb files into the repo that would be great in a `data/` folder

**Comment by xnought** [comment]
https://www.biostat.jhsph.edu/~iruczins/teaching/260.655/links/pdbformat.pdf looks like a good resource

**Comment by ansengarvin** [comment]
Sorry for the late response on this issue! Evidently, my github account doesn't send emails to my school account (which I check daily), but instead sends it to my personal account (which I check rarely.)

I'll be able to look into these files once I'm done with the individual SDP document, and a machine learning quiz. That resource you linked looks like a great place to start!

I'm also going to see if I can forward github notifications to my school email.

**Comment by xnought** [comment]
No rush! To be honest, we should first assign roles and align on the requirements first. We can do that at the monday meeting. So don't do anything till then!
