### ISSUE TITLE
upload_all script is broken

### ISSUE THREAD

**Issue by xnought** [xnought/venome#183]
Since we lock the upload all script maybe we can have an override key that only us developers know about so we can stilll upload from our end using that post request to upload

**Comment by xnought** [comment]
Or we request and add a token directly to the headers of each request in the [`upload_all.py`](https://github.com/xnought/venome/blob/main/galaxy/upload_all.py#L29) file

**Comment by ansengarvin** [comment]
I think the best solution is to submit a single login request at the start (using the test account's credentials) then submitting that token as a header. I'll try to fix it.

**Comment by xnought** [comment]
cool let me know if I can help
