### ISSUE TITLE
TMAlign show the alignment info string

### ISSUE THREAD

**Issue by xnought** [xnought/venome#239]

**Comment by ansengarvin** [comment]
Started working on this here: https://github.com/xnought/venome/tree/sequence_align

So far I've written an API endpoint which returns only the relevant string format, broken up into an array to (hopefully) make it easier to work with in the front end:

https://media.discordapp.net/attachments/1164670587231289496/1230707325866737716/image.png?ex=66344c83&is=6621d783&hm=345211418783d37bc30bf9c807b2c3b03e76791eaf60dd1b9e14c2de0a1c3a9c&=&format=webp&quality=lossless&width=1440&height=429
